name: Lint

on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Run Typecheck
        run: npm run typecheck
